/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountPlayerMemberDialog: typeof import('./src/components/dialogs/AccountPlayerMemberDialog.vue')['default']
    AuctionStage: typeof import('./src/components/auction/AuctionStage.vue')['default']
    CupMemberDialog: typeof import('./src/components/dialogs/CupMemberDialog.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    HeaderNav: typeof import('./src/components/header/HeaderNav.vue')['default']
    PlayerMemberDialog: typeof import('./src/components/dialogs/PlayerMemberDialog.vue')['default']
    ProjectMemberDialog: typeof import('./src/components/dialogs/ProjectMemberDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerDataTable: typeof import('./src/components/common/ServerDataTable.vue')['default']
  }
}
