/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/board/': RouteRecordInfo<'/board/', '/board', Record<never, never>, Record<never, never>>,
    '/board/add': RouteRecordInfo<'/board/add', '/board/add', Record<never, never>, Record<never, never>>,
    '/board/view': RouteRecordInfo<'/board/view', '/board/view', Record<never, never>, Record<never, never>>,
    '/clan/': RouteRecordInfo<'/clan/', '/clan', Record<never, never>, Record<never, never>>,
    '/clan/account/': RouteRecordInfo<'/clan/account/', '/clan/account', Record<never, never>, Record<never, never>>,
    '/clan/account/view': RouteRecordInfo<'/clan/account/view', '/clan/account/view', Record<never, never>, Record<never, never>>,
    '/clan/board/': RouteRecordInfo<'/clan/board/', '/clan/board', Record<never, never>, Record<never, never>>,
    '/clan/board/add': RouteRecordInfo<'/clan/board/add', '/clan/board/add', Record<never, never>, Record<never, never>>,
    '/clan/board/view': RouteRecordInfo<'/clan/board/view', '/clan/board/view', Record<never, never>, Record<never, never>>,
    '/clan/enquire/': RouteRecordInfo<'/clan/enquire/', '/clan/enquire', Record<never, never>, Record<never, never>>,
    '/clan/enquire/add': RouteRecordInfo<'/clan/enquire/add', '/clan/enquire/add', Record<never, never>, Record<never, never>>,
    '/clan/enquire/view': RouteRecordInfo<'/clan/enquire/view', '/clan/enquire/view', Record<never, never>, Record<never, never>>,
    '/clan/myclan': RouteRecordInfo<'/clan/myclan', '/clan/myclan', Record<never, never>, Record<never, never>>,
    '/clan/player': RouteRecordInfo<'/clan/player', '/clan/player', Record<never, never>, Record<never, never>>,
    '/config/': RouteRecordInfo<'/config/', '/config', Record<never, never>, Record<never, never>>,
    '/config/account/': RouteRecordInfo<'/config/account/', '/config/account', Record<never, never>, Record<never, never>>,
    '/config/account/view': RouteRecordInfo<'/config/account/view', '/config/account/view', Record<never, never>, Record<never, never>>,
    '/config/permission/clan/': RouteRecordInfo<'/config/permission/clan/', '/config/permission/clan', Record<never, never>, Record<never, never>>,
    '/config/permission/system/': RouteRecordInfo<'/config/permission/system/', '/config/permission/system', Record<never, never>, Record<never, never>>,
    '/config/player/': RouteRecordInfo<'/config/player/', '/config/player', Record<never, never>, Record<never, never>>,
    '/config/profile/': RouteRecordInfo<'/config/profile/', '/config/profile', Record<never, never>, Record<never, never>>,
    '/config/tier/': RouteRecordInfo<'/config/tier/', '/config/tier', Record<never, never>, Record<never, never>>,
    '/cup/': RouteRecordInfo<'/cup/', '/cup', Record<never, never>, Record<never, never>>,
    '/cup/add': RouteRecordInfo<'/cup/add', '/cup/add', Record<never, never>, Record<never, never>>,
    '/cup/bracket': RouteRecordInfo<'/cup/bracket', '/cup/bracket', Record<never, never>, Record<never, never>>,
    '/cup/view': RouteRecordInfo<'/cup/view', '/cup/view', Record<never, never>, Record<never, never>>,
    '/enquire/': RouteRecordInfo<'/enquire/', '/enquire', Record<never, never>, Record<never, never>>,
    '/enquire/add': RouteRecordInfo<'/enquire/add', '/enquire/add', Record<never, never>, Record<never, never>>,
    '/enquire/view': RouteRecordInfo<'/enquire/view', '/enquire/view', Record<never, never>, Record<never, never>>,
    '/exception/Exception': RouteRecordInfo<'/exception/Exception', '/exception/Exception', Record<never, never>, Record<never, never>>,
    '/forum/': RouteRecordInfo<'/forum/', '/forum', Record<never, never>, Record<never, never>>,
    '/forum/add': RouteRecordInfo<'/forum/add', '/forum/add', Record<never, never>, Record<never, never>>,
    '/forum/view': RouteRecordInfo<'/forum/view', '/forum/view', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/login/KakaoLolRegister': RouteRecordInfo<'/login/KakaoLolRegister', '/login/KakaoLolRegister', Record<never, never>, Record<never, never>>,
    '/login/PendingApproval': RouteRecordInfo<'/login/PendingApproval', '/login/PendingApproval', Record<never, never>, Record<never, never>>,
    '/match/': RouteRecordInfo<'/match/', '/match', Record<never, never>, Record<never, never>>,
    '/match/add': RouteRecordInfo<'/match/add', '/match/add', Record<never, never>, Record<never, never>>,
    '/match/view': RouteRecordInfo<'/match/view', '/match/view', Record<never, never>, Record<never, never>>,
    '/record/': RouteRecordInfo<'/record/', '/record', Record<never, never>, Record<never, never>>,
  }
}
